services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"    # AMQP protocol (for services)
      - "15672:15672"  # Management UI (browser access)
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - microservices-network

  mongo-auth:
    image: mongo:latest
    container_name: mongo-auth
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpass
    volumes:
      - mongo_auth_data:/data/db
    networks:
      - microservices-network

  mongo-product:
    image: mongo:latest
    container_name: mongo-product
    restart: always
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpass
    volumes:
      - mongo_product_data:/data/db
    networks:
      - microservices-network

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "3000:3000"
    env_file:
      - .env.example-auth
    depends_on:
      - mongo-auth
      - rabbitmq
    networks:
      - microservices-network

  product-service:
    build: ./product-service
    container_name: product-service
    ports:
      - "3001:3001"
    env_file:
      - .env.example-product
    depends_on:
      - mongo-product
      - rabbitmq
      - auth-service
    networks:
      - microservices-network

volumes:
  rabbitmq_data:
  mongo_auth_data:
  mongo_product_data:

networks:
  microservices-network:
    driver: bridge
